myproject/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

myproject/app/models.py
from django.db import models

# Create your models here.

myproject/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed
from django import forms

users = ['Вася Питонов', 'Петя Гадюкин']


class UserForm(forms.Form):
    first_name = forms.CharField(
        max_length=100,
        min_length=5,
        label='Имя'
    )
    last_name = forms.CharField(
        max_length=100,
        min_length=5,
        label='Фамилия'
    )


def index(request):
    context = {
        'users': users
    }
    return render(request, 'app/index.html', context)


def add(request):
    if request.method == 'GET':
        form_fields = UserForm()
        context = {
            'form_fields': form_fields
        }
        return render(request, 'app/add.html', context)
    elif request.method == 'POST':
        form_fields = UserForm(request.POST)
        if form_fields.is_valid():
            first_name = form_fields.cleaned_data['first_name']
            last_name = form_fields.cleaned_data['last_name']
            user = first_name + ' ' + last_name
            users.append(user)
            return redirect('app:index')
        else:
            return render(request, 'app/add.html', context)
    else:
        return HttpResponseNotAllowed(
            ['POST', 'GET'],
            content='Ошибка Этот метод не разрешен!'
        )

myproject/app/templates/app/add.html
{% extends "app/base.html" %}

{% block title %}
   Привет!
{% endblock %}

{% block body %}
<form action="{% url 'app:add' %}" method="POST">
   {% csrf_token %}
   {{ form_fields.as_p }}
   <input type="submit">
</form>
<a href="{% url 'app:index' %}">на главную страницу</a>
{% endblock %}

myproject/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

myproject/app/templates/app/index.html
{% extends "app/base.html" %}

{% block title %}
    Запросы
{% endblock %}

{% block body %}
<ol>
    {% for user in users %}
    <li>{{ user }}</li>
    {% endfor %}
</ol>
<a href="{% url 'app:add' %}">добавить пользователя</a>
{% endblock %}